### PR TITLE
Deactivate buttons for reload command after button click

### PR DESCRIPTION
**Pull request by talentedasian**
- Disable buttons after being used
- Added ephemeral explanation message to users clicking the buttons if they are not the user who triggered the command originally
- Finishing touches

[contributing]: https://github.com/Together-Java/TJ-Bot/wiki/Contributing
[code_guidelines]: https://github.com/Together-Java/TJ-Bot/wiki/Code-Guidelines
[new_issue]: https://github.com/Together-Java/TJ-Bot/issues/new/choose

## Pull-request

- [x] I have read the [contributing guidelines][contributing].
- [x] I have read the [code guidelines][code_guidelines].
- [x] I have created a relating [issue][new_issue].

### Changes

- [x] Existing code
- [x] New feature

Closes Issue: #167

## Description

This PR does not have any Junit tests but are tested on my own server(button interactions only).
 It was a pain in the ass to even think about it.
image

### CODE REVIEW

**Comment by Zabuzard** [comment]
> 
> 
> > While at it, mind adding an ephemeral message if an user who is not allowed to click the button clicks.
> 
> Do you mean if a user who isn't allowed to click(assuming the user isn't the author) the button for the `/reload` command clicks it?

Exactly. If I recall correctly, the code checks the user ID and if it does not match it just `return;` without any message to the user. So the user could be confused and think something is broken. It could help if the bot instead sends an ephemeral message to the user, telling him that only the original author can use the buttons.

**Comment by Tais993** [comment]
image
Unrelated, but replace the / with an x

- [x] This looks a lot better, doesn't it? :P

**Comment by Zabuzard** [comment]
@talentedasian May I ask, what is your Discord name? Once this is merged, I can grant you the contributor role then 👍 By the way, awesome job, well done! 🎉

**Comment by talentedasian** [comment]
> @talentedasian May I ask, what is your Discord name? Once this is merged, I can grant you the contributor role then +1 By the way, awesome job, well done! tada

I'm asianmalaysian vietnamese :)

**Pull request merged**
