### PR TITLE
improve suggestion for archived thread due to inactivity

### LINKED ISSUE #923: Auto-detect inactivty and send hint for help-threads
When creating a help-thread, we send a few hints.

One of them is how to act when no one responds. Our entry point for this hint is bad. It would be better if we post this message when the moment of inactivity has come.

hint

So we should detect when a thread is inactive (no one except OP responded since 5 hours) and then let the bot automatically post this message. This will also lead to an "auto-bump", which may cause more helper attention.

### PR DESCRIPTION
**Pull request by ankitsmt211**
* more emphasis on reasons for thread inactivity

updated:

image

resolves #923

### CODE REVIEW

**Comment by Zabuzard** [comment]
To resolve the linked issue, u also have to remove the text from the thread-opening bot response

**Comment by Zabuzard** [comment]
I propose to rephrase as:

> Closed the thread due to inactivity.
> 
> If your question was not resolved yet, feel free to just post a message below to reopen it, or create a new thread.
>
> Note that usually the reason for nobody calling back is that your question may have been **not well asked** and hence no one felt confident enough answering. When you reopen the thread, try to use your time to **improve the quality** of the question by elaborating, providing details, context, all relevant code snippets, any errors you are getting, concrete examples and perhaps also some screenshots. Share your attempt, explain the expected results and compare them to the current results. Also try to make the information easily accessible by sharing code or assignment descriptions directly on Discord, not behind a link or pdf file; provide some guidance for long code snippets and ensure the code is well formatted and has syntax highlighting. Kindly read through https://stackoverflow.com/help/how-to-ask for more.
>
> With enough info, someone knows the answer for sure 👍

**Review by Zabuzard — CHANGES_REQUESTED** [review]
(see my comments)

**Review by Taz03 — DISMISSED** [review]

**Review by Zabuzard — COMMENTED** [review]
can u share a screenshot of how it looks in action? :)

**Comment by Zabuzard** [comment]
well, u already did. lol

**Review by Taz03 — DISMISSED** [review]
😃

**Review by Zabuzard — CHANGES_REQUESTED** [review]
Sorry, but something I just noticed is that the response does not ping OP. That causes the thread to "vanish" and OP has a hard time finding it again.

I guess a ping would be useful. Make sure that the ping is outside of the embed, in the "message", otherwise it does not actually ping.

Could you add that while at it?

**Review by Zabuzard — APPROVED** [review]

**Review by Taz03 — APPROVED** [review]

**Pull request merged**
