### PR TITLE
fixed unknown author bug

### LINKED ISSUE #522: Audit can not retrieve users anymore
The recent merge #472 messed up the ability for `/audit` to retrieve the actual users who used the actions against the target.

See the following example:

example

## Reason

The bug comes from exchanging the previously correct
```java
jda.retrieveUserById(action.authorId())
```
by the wrong
```java
jda.getUserById(action.authorId());
```

Latter only checks the JDA cache instead of asking Discord. The cache is rarely reliable (only for the list of guilds).

Changing this back is fairly simple, but requires to make the code properly async using `RestAction`.

### PR DESCRIPTION
**Pull request by Taz03**
closes #522

### CODE REVIEW

**Review by Zabuzard — CHANGES_REQUESTED** [review]
now you are blocking the thread. thats wrong. you have to do a proper RestAction chain like the code did in the past.

```java
jda.retrieve...(...)
  .map(...)
  .map(...)
  .flatMap(...)
  .queue()
```
u gotta learn how to do proper multithreading when working with such stuff :)

**Comment by Taz03** [comment]
i've used the same method at one more place in the code [here](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java#L182) should that be changed too?

**Comment by Zabuzard** [comment]
> i've used the same method at one more place in the code [here](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java#L182) should that be changed too?

oof, yes. you are blocking the JDA thread there.

**Comment by Taz03** [comment]
> now you are blocking the thread. thats wrong. you have to do a proper RestAction chain like the code did in the past.
> 
> ```java
> jda.retrieve...(...)
>   .map(...)
>   .map(...)
>   .flatMap(...)
>   .queue()
> ```
> 
> u gotta learn how to do proper multithreading when working with such stuff :)

as of now i dont know how to do that so maybe someone else should do this

**Pull request closed without merging**
