### PR TITLE
Style: changed delete icon for CodeMessageHandler

### LINKED ISSUE #787: Use text to remove ambiguity of buttons.
**Is your feature request related to a problem? Please describe.**
The delete tool button is ambiguous. I was unsure whether it meant do delete the bots message, my message, the code snippet or otherwise. I had to ask someone else, which means it's bad UI design. Aesthetic should not compromise usability.
image

**Describe the solution you'd like**
Simply replace the bin emoji with "delete this message" or similar.

**Describe alternatives you've considered**
n/a

**Additional context**
See screenshot.

Are there any additional places emojis are being used in favor of text to represent an action that could be ambiguous?

### PR DESCRIPTION
**Pull request by swashb0ckler**
Changed the icon with a basket to a simple 'Dismiss' 

closes #787

### CODE REVIEW

**Review by Taz03 — APPROVED** [review]

**Comment by Taz03** [comment]
@swashb0ckler all u have to do now is just [sign the cla](https://github.com/Together-Java/TJ-Bot/pull/793#issuecomment-1450365199)

**Comment by Taz03** [comment]
@swashb0ckler also u should post the image here in the pr so other reviewers will see that

**Review by Zabuzard — APPROVED** [review]

**Comment by swashb0ckler** [comment]
Like this? 
image

**Comment by Taz03** [comment]
yes

**Pull request merged**
