### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by Zabuzard**
After this is merged, Pull Requests will require code reviews from Code Owners (mods and staff helpers).

This prevents that some random has some shitty PR and his friends just wave it through and it gets merged.

### CODE REVIEW

**Review by d3vel0per — APPROVED** [review]
I don't know what this configuration specifically does but I agree in principle

**Review by I-Al-Istannen — APPROVED** [review]

**Comment by marko-radosavljevic** [comment]
Yeah, also not completely sure how this works. I thought only people with write permissions can merge?

Or this is more quality of life feature, so you can easily see/enforce 2 people with write permissions reviewed?

**Comment by java-coding-prodigy** [comment]
so now all staff helpers will have to review a PR?

**Comment by Zabuzard** [comment]
> 
> 
> Yeah, also not completely sure how this works. I thought only people with write permissions can merge?
> 
> Or this is more quality of life feature, so you can easily see/enforce 2 people with write permissions reviewed?

Now Code Reviews have to be from the staff team and not from randoms. That way we can ensure quality.

Merging can be done by anyone as long as all the reviews passed, the CI/CD is happy and discussions are resolved.

**Comment by Zabuzard** [comment]
> 
> 
> so now all staff helpers will have to review a PR?

It means that each PR has to be reviewed by at least 2 people from the staff team.

**Comment by java-coding-prodigy** [comment]
> It means that each PR has to be reviewed by at least 2 people from the staff team.

But.. it already is like that, isn't it?

**Pull request merged**
