### PR TITLE
Release 2.0

### PR DESCRIPTION
**Pull request by Zabuzard**
### Overview

This marks the first release towards the **Migrate existing commands** objective, version **2.0**.

It contains various commands, such as:
* tag system
* moderation commands
* mod audit log
* TeX command
* voice chat activities

### Plan

The plan is to release in a few days (**Friday, 19. Nov. 2021**), unless **develop** revealed any unstability in the recently merged features.

It is possible that the release gets delayed for a bit if any important features should be included short-term.

### Checklist

* [x] ~~Wait for #252~~
* [x] Wait for #254 
* [x] ~~(Wait for #221 ?)~~
* [x] ~~(Wait for #207 ?)~~
* [x] Wait until release date
* [x] Increase permissions of bot in main server (re-invite)
* [x] Create `mod_audit_log` channel in main server
* [x] Force-push `develop` to `master`
* [x] Create and push an annotated release tag
* [x] Adjust `config.json` of **master-bot** on VPS
* [x] Restart bot
* [x] `/reload` in main server
* [x] quick stability test

### CODE REVIEW

**Comment by illuminator3** [comment]
Could we please wait for the bytecode command? I'm pretty sure a lot of members would want that command on the main server.

**Comment by Zabuzard** [comment]
> 
> 
> Could we please wait for the bytecode command? I'm pretty sure a lot of members would want that command on the main server.

Have a rough ETA for that? That said, I also dont see any problem in having another release a few weeks after.

**Comment by java-coding-prodigy** [comment]
Also, do wait for wolf command, it is not very useful but it would suck if it got delayed by 6 months for this.
It will most likely get completed by next week anyway, so before bytecode command for sure.

**Comment by Tais993** [comment]
> I also dont see any problem in having another release 1-2 weeks after.

No-one ever said 6 months and that's way too long.

We shouldn't constantly delay releases, so we'll see whenever that the Wolfram alpha command gets added.

Otherwise, 1/2 weeks

**Comment by java-coding-prodigy** [comment]
> We shouldn't constantly delay releases, so we'll see whenever that the Wolfram alpha command gets added.

Like I said, probably next week.

**Comment by Zabuzard** [comment]
> 
> 
> > We shouldn't constantly delay releases, so we'll see whenever that the Wolfram alpha command gets added.
> 
> Like I said, probably next week.

Dont forget that features also have to be released and tested successfully for about a week on the develop server at least.

I doubt your feature will make it into this release. I also doubt free will make it. But thats okay, we will just ship another release in 2 weeks or so...

**Comment by java-coding-prodigy** [comment]
So neither will bytecode make it I guess...

**Pull request merged**
