### PR TITLE
Update JDA version

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
This update includes:

add support for min/max option value (#1863)

Implement user banner & banner color (#1736)

Updated magic numbers to use the Message#MAX_CONTENT_LENGTH constant (#1870)

 add BOT_HTTP_INTERACTIONS user flag (#1865)

Added whoami as command to the MessageListenerExample which sends id,… (#1866)

Attempt a fix for overriding messages

### CODE REVIEW

**Comment by Zabuzard** [comment]
Any reason why we need this **now** instead of waiting till the next dependabot update at the end of the month? The only thing in the list you shared that could be interesting for us today would be

* add support for min/max option value (#1863)

and we already solved that problem with the choice-system thing

**Comment by RealYusufIsmail** [comment]
I could use min/max for the user id instead of keeping as a string I can limit it to a certain number of value

**Comment by Zabuzard** [comment]
> 
> 
> I could use min/max for the user id instead of keeping as a string I can limit it to a certain number of value

for what user id? doesnt sound reasonable to me.

**Comment by RealYusufIsmail** [comment]
> > I could use min/max for the user id instead of keeping as a string I can limit it to a certain number of value
> 
> for what user id? doesnt sound reasonable to me.

I mean like `/warn userid`. To make sure the user does not enter a value bigger than a user id

**Comment by Tais993** [comment]
> 
> 
> > > I could use min/max for the user id instead of keeping as a string I can limit it to a certain number of value
> > 
> > 
> > for what user id? doesnt sound reasonable to me.
> 
> I mean like `/warn userid`. To make sure the user does not enter a value bigger than a user id

You should use the OptionType#USER instead

**Comment by Zabuzard** [comment]
If there is no real need for this, I say we close this and go with the next automatic update based on dependabot.

**Comment by RealYusufIsmail** [comment]
Ok

**Pull request closed without merging**
