### PR TITLE
Add sonarlint

### PR DESCRIPTION
**Pull request by marko-radosavljevic**
Adds sonarlint so we have basic linting inside PRs from forks.

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
The issue with it is that it fails the build on every violation, which is not how it's currently working.

To suppress a violation this can be done: [link](https://stackoverflow.com/a/39109612).

**Comment by I-Al-Istannen** [comment]
> The issue with it is that it fails the build on every violation, which is not how it's currently working.
> 
> To suppress a violation this can be done: [link](https://stackoverflow.com/a/39109612).

I think you can disable them with a comment / SuppressWarnings?

**Comment by marko-radosavljevic** [comment]
Yup, that's on the link I posted.

If you have the id of the rule you want to ignore, annotation:
`@SuppressWarnings("squid:S0016")`

Or a comment:
`//NOSONAR`

> The issue with it is that it fails the build on every violation, which is not how it's currently working.

This issue can also be seen as a feature, because you get to see all the violations on build, and you can fix them before pushing. I can also implement a flag to turn it on/off on build too, will do that later today.

**Comment by I-Al-Istannen** [comment]
I would probably refrain from merging this until the issues it fails on are resolved? I am not sure whether a failing develop build is a good idea?

**Comment by marko-radosavljevic** [comment]
Yes, that's the idea, wait for violations to be fixed before merging. ^^

Are you working on that @I-Al-Istannen, or you want someone else to pick it up?

**Review by Zabuzard — APPROVED** [review]

**Comment by Zabuzard** [comment]
> 
> 
> Yes, that's the idea, wait for violations to be fixed before merging. ^^
> 
> Are you working on that @I-Al-Istannen, or you want someone else to pick it up?

If this takes too long, I would vote for merging just to put more pressure on it and to prevent that the state gets worse the more is merged.

**Comment by I-Al-Istannen** [comment]
Ah I missed that comment and I wasn't, but I can give it a shot on the current develop branch.

**Review by I-Al-Istannen — APPROVED** [review]

**Pull request merged**
