### PR TITLE
Update gradle to 7.3

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
Fixes a number of issue including the issue were gradle did not support java 17 but now with gradle 7.3 java 17 is supported

Fixes the issue https://github.com/Together-Java/TJ-Bot/issues/257

All the fixes can be found here: https://docs.gradle.org/7.3/release-notes.html

### CODE REVIEW

**Review by Tais993 — APPROVED** [review]

**Comment by Zabuzard** [comment]
Please someone ensure to check this through so that it actually works.

**Comment by RealYusufIsmail** [comment]
> Please someone ensure to check this through so that it actually works.

It does I will send a screen shot as proof

**Comment by Tais993** [comment]
> 
> 
> Please someone ensure to check this through so that it actually works.

It does work indeed

**Review by Zabuzard — APPROVED** [review]

**Comment by java-coding-prodigy** [comment]
Should we rebase this commit to our branches as it is very important

**Comment by Zabuzard** [comment]
u should always rebase with develop. up to u when u do it but latest when ur PR is ready, u have to do it otherwise github wont even allow the PR.

**Comment by RealYusufIsmail** [comment]
Am I able to join the team now?

**Comment by Zabuzard** [comment]
> 
> 
> Am I able to join the team now?

I will add you soon. You have to learn to have some patience^^

**Comment by RealYusufIsmail** [comment]
Ok.

**Pull request merged**
