### PR TITLE
Bump up java level

### PR DESCRIPTION
**Pull request by java-coding-prodigy**
Bump up the java level from 16 to 17 now that it has released.

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Hi, welcome to our repo! :relaxed: :heart:

Make sure to read our [contributing guidlines](https://github.com/Together-Java/TJ-Bot/wiki/Contributing).

Some recommendations:
- Open an issue first to discuss your changes with the community before submitting an PR. This way we also avoid duplicated work. ^^
- A pull request should only implement one feature or bugfix. If you want to add or fix more than one thing, please submit another pull request. You are bumping java version, but also touching 5 other unrelated files.
- Make sure to run `./gradlew spotlessApply` to fix code style violations before pushing your changes.

**Comment by krankkkk** [comment]
This should wait until there are more JDK's  available than just the Oracle one. Adoptium is planning it's release on the 30. i.e.
If you set this it would mean only people who have an Java 17 JDK can work on it and every server that runs the bot also needs to be on 17 and not every OS has such an installer available yet

**Comment by java-coding-prodigy** [comment]
> A pull request should only implement one feature or bugfix. If you want to add or fix more than one thing, please submit another pull request. You are bumping java version, but also touching 5 other unrelated files.

I only meant to touch the 3 files.
the other 5 files were changed in a different commit which I added accidently but now do not know how to remove.
As for the other guidelines, yes I will keep that in mind.

**Comment by java-coding-prodigy** [comment]
https://github.com/java-coding-prodigy/TJ-Bot/commit/5f90fdba172e7ab1f8e34f6c971b7d895189b49b This commit was unintended, the other 2 have the required changes.

**Comment by krankkkk** [comment]
Also why are the changes on the very first lines of the script? They should be in the compileJava Task

**Comment by java-coding-prodigy** [comment]
What exactly do you mean? I replaced all instances of `VERSION.16` to `VERSION.18`

**Review by illuminator3 — CHANGES_REQUESTED** [review]
apply our formatting using spotless

**Comment by Zabuzard** [comment]
Please review your diff. There are some edits that do not seem to be related to changing the version in the first place.

Other than that, upgrading to 17 is good! We will hold this PR back a little though until people can at least get it on Adoptium.

**Comment by Zabuzard** [comment]
Java 17 is now available on Adoptium. We will make the switch in the next days. If you do not plan to continue this branch anymore, someone will take over.

**Comment by marko-radosavljevic** [comment]
Due to inactivity, closing this in favor of competing #148.

Thanks for your efforts tho, we appreciate it! ^^

**Pull request closed without merging**
