### PR TITLE
Migrate TeX command

### PR DESCRIPTION
**Pull request by java-coding-prodigy**
Partially implements #128 

Adds  the `/tex` command.

### CODE REVIEW

**Comment by Zabuzard** [comment]
I am curious, could you share a screenshot of an example conversation with the bot using that command? How does it look like? 🤔

**Comment by Zabuzard** [comment]
To cleanup ur history, id suggest you do a mixed-reset, stash the changes, rebase `develop`, pop the stash, only re-apply the actual latex command related changes (the dependency, the class, the png file), create a commit of that, force-push.

**Comment by java-coding-prodigy** [comment]
I think now we should start working on our buttons

**Comment by java-coding-prodigy** [comment]
After discussing in the discord, we were unable to find a way to `Edit` the message without the user sending a separate message. imo this voids the use of the Edit button and therefore I will be removing it.

**Comment by Tais993** [comment]
On that note, Discord is developing a way to request user input (text) after a.e button presses.

Once that's finalized the edit feature could become something really cool.
So maybe in the future again

**Comment by Zabuzard** [comment]
As a note to whoever merges this PR (probably me, lol), it fits a squash perfectly.

**Pull request merged**
