### PR TITLE
Update JDA-4 to JDA-5 alpha 9

### PR DESCRIPTION
**Pull request by Tais993**
[contributing]: https://github.com/Together-Java/TJ-Bot/wiki/Contributing
[code_guidelines]: https://github.com/Together-Java/TJ-Bot/wiki/Code-Guidelines
[new_issue]: https://github.com/Together-Java/TJ-Bot/issues/new/choose

## Pull-request

- [x] I have read the [contributing guidelines][contributing].
- [x] I have read the [code guidelines][code_guidelines].
- [x] I have created a relating [issue][new_issue].

### Changes

- [x] Existing code
- [ ] New feature

Closes Issue: #407 

## Description

This PR updates our project to use JDA-5 alpha 9, unlike the name might suggest, this is a stable release, but more prone to breaking changes when upgrading.
This adds support for auto-complete, time-outs, threads, context-menu's and possibly more.
To use some features, we need #368 to get merged.
In the main-time, this still adds support for other features.

### CODE REVIEW

**Review by illuminator3 — APPROVED** [review]
LGTM

**Review by Zabuzard — APPROVED** [review]
Lots of changes, but they all seem to be kinda boring and trivial. So LGTM.

**Comment by Tais993** [comment]
Could you rerun the license? @Zabuzard

**Comment by Zabuzard** [comment]
Done

**Pull request merged**
