### PR TITLE
use - in channel names

### PR DESCRIPTION
**Pull request by Taz03**

### CODE REVIEW

**Comment by Nxllpointer** [comment]
But why

**Comment by Nxllpointer** [comment]
Also read the [branch naming guidelines](https://github.com/Together-Java/TJ-Bot/wiki/Contributing#create-a-fork) again

**Comment by SquidXTV** [comment]
> But why
https://discord.com/channels/272761734820003841/480829495486447627/1113378742182629437
voted for in server suggestions

**Comment by Nxllpointer** [comment]
oh ok

**Review by Zabuzard — APPROVED** [review]

**Comment by Taz03** [comment]
😀

**Pull request merged**
