### PR TITLE
added comma for clarity

### PR DESCRIPTION
**Pull request by moki929**
minor grammar improvement

### CODE REVIEW

**Comment by Zabuzard** [comment]
Cool, thank you :) One of the "nobody asked for this, but fair" improvements, haha. Appreciate it 👍

**Review by Zabuzard — APPROVED** [review]

**Comment by Zabuzard** [comment]
Are you in our Discord server? If you tell me your name, I can add you to the "Community Bot Contributor" role, if you want.

**Comment by moki929** [comment]
> Are you in our Discord server? If you tell me your name, I can add you to the "Community Bot Contributor" role, if you want.

Yes, I'm @MoKi#8640 on Discord

**Review by illuminator3 — APPROVED** [review]

**Review by Taz03 — APPROVED** [review]

**Comment by marko-radosavljevic** [comment]
Merged, thank you for your contribution! :relaxed: :heart:

**Pull request merged**
