### PR TITLE
Bump Java Version to 17

### LINKED ISSUE #147: Bump Java Version to 17
With Adoptium now having released its Version of OpenJDK on [all major platforms](https://github.com/adoptium/adoptium/issues/74), we can now officially switch to Java 17.

### PR DESCRIPTION
**Pull request by krankkkk**
Change only in the main Gradle buildscript necessary

Closes #147

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Hi, thanks for contributing! :relaxed: :heart: 

I ran the checks for you, and I assume everything works locally?

Java version of GitHub workflows also has to be updated, you can find them here: [link](https://github.com/Together-Java/TJ-Bot/tree/develop/.github/workflows). ^^

**Comment by krankkkk** [comment]
Also updated the workflows.
Yes locally everything works just fine

**Comment by krankkkk** [comment]
SonarCloud failed with `You're not authorized to run analysis. Please contact the project administrator`, can't fix that

**Review by marko-radosavljevic — DISMISSED** [review]
Looks good, thanks!

This was too easy tho, I'm a bit suspicious, but let's find out what happens after the merge. ^^

**Comment by marko-radosavljevic** [comment]
> SonarCloud failed with `You're not authorized to run analysis. Please contact the project administrator`, can't fix that

Yup, that's expected, don't worry about it.

**Comment by krankkkk** [comment]
Before merging someone should probably install the new JDK on the VPS, else the Bot won't run anymore

**Comment by marko-radosavljevic** [comment]
> Before merging someone should probably install the new JDK on the VPS, else the Bot won't run anymore

@I-Al-Istannen

**Comment by I-Al-Istannen** [comment]
> > Before merging someone should probably install the new JDK on the VPS, else the Bot won't run anymore
> 
> @I-Al-Istannen

That is handled by the docker image build by `gradle jib`, you can adjust that in `application/build.gradle`.

**Comment by krankkkk** [comment]
If you are using the dockerised variant we gotta wait again until they release an jdk17 on docker.

> > > Before merging someone should probably install the new JDK on the VPS, else the Bot won't run anymore
> > 
> > 
> > @I-Al-Istannen
> 
> That is handled by the docker image build by `gradle jib`, you can adjust that in `application/build.gradle`.

there is no alpine version of the the 17-JDK from Adoptium yet, do you want to wait for it?

**Comment by I-Al-Istannen** [comment]
We should migrate to [temurin](https://hub.docker.com/_/eclipse-temurin/) 17 (without alpine is fine) as Adoptopenjdk is officially superceded by Eclipse Temurin.

**Comment by krankkkk** [comment]
> We should migrate to [temurin](https://hub.docker.com/_/eclipse-temurin/) 17 (without alpine is fine) as Adoptopenjdk is officially superceded by Eclipse Temurin.

Found that too, was just confused about the alpine-slim part since it's not yet finished. Fixed now.

**Review by illuminator3 — APPROVED** [review]
LGTM

**Review by marko-radosavljevic — APPROVED** [review]

**Comment by marko-radosavljevic** [comment]
Thanks for updating your commit and keeping the history clean, I appreciate it. :heart:

Since nobody objected, I'm merging this.

**Pull request merged**
