### PR TITLE
Fix bug with /audit unable to retrieve users

### LINKED ISSUE #522: Audit can not retrieve users anymore
The recent merge #472 messed up the ability for `/audit` to retrieve the actual users who used the actions against the target.

See the following example:

example

## Reason

The bug comes from exchanging the previously correct
```java
jda.retrieveUserById(action.authorId())
```
by the wrong
```java
jda.getUserById(action.authorId());
```

Latter only checks the JDA cache instead of asking Discord. The cache is rarely reliable (only for the list of guilds).

Changing this back is fairly simple, but requires to make the code properly async using `RestAction`.

### PR DESCRIPTION
**Pull request by Zabuzard**
## Overview

The latest rework of `/audit` messed up some stuff and had a few bugs. This fixes it, closes #522 .

## Details

The most prominent issue was incorrect usage of JDAs actions: `jda.retrieveUserById(id).complete()` which blocked the JDA thread and `jda.getUserById(id)` which looked up (outdated) cache, failing to find the user.

The issue has been fixed by properly using `RestAction`s and their `map/flatMap` chains. Obviously this uglifies the code a bit - but many new helper methods to the rescue.

Apart from that, there have been some minor improvements on the UX:
* show no page buttons if there is only a single page
* display the last page by default (most recent entries)
* max page size 10 for better visibility

As well as a few code readability improvements here and there, and some minor safety bugfixes like `page <= 1`, `page >= totalPages` instead of `==` checks.

Last, the methods have been re-ordered in time they are used to increase the readability flow - unfortunately that makes the review a bit nasty due to bad GitHub diffing.

## Tests

Improvements are well tested, all edge cases included:

* User totally unknown to the guild (= user with no actions):
unknown user

* User with one page actions
one page

* User with many pages actions (max page size was reduced to 3 for the test)
last page

### CODE REVIEW

**Comment by Zabuzard** [comment]
(@Taz03 for visibility)

**Review by marko-radosavljevic — DISMISSED** [review]

**Comment by marko-radosavljevic** [comment]
I like the new order of methods and refactorings. It did make the review a lot harder tho haha :heart:

**Comment by Zabuzard** [comment]
rebase, no code change

**Review by marko-radosavljevic — APPROVED** [review]

**Comment by Zabuzard** [comment]
Merging this, seems to be fine - if not, we can act afterwards. Want to accelerate development for this, need to get out a release for all the major improvements. Also, its weekened and I want to code a bit 😄

**Pull request merged**
